version: '3.7'

services:
  web:
    build: ./SRLMS
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./SRLMS:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=srlmsdb
      - POSTGRES_DB=srlmsdb

volumes:
  postgres_data: